name: Build & Publish
on:
  push:
    branches:
      - dev
      - staging
      - prod
  pull_request:
    branches:
      - main

jobs:
  docker-build-publish:
    name: ${{ matrix.environment }}
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: dev
          - environment: staging
          - environment: prod
              
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set output
        run: echo "provider=Azure" >> $GITHUB_OUTPUT

      - name: Check out
        uses: actions/checkout@v3
      
      - name: Set environment
        run: |
              echo "Setting state for ${{ matrix.environment }}"

      - name: checking Build
        run: |
          echo "Hello"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: docker-build-publish
    if: github.ref == 'refs/heads/dev'
    environment:
      name: "development"
    
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: checking deploy
        run: |
          echo "Hello-dev"


  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker-build-publish
    if: github.ref == 'refs/heads/staging'
    environment:
      name: "development"
    
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: checking deploy
        run: |
          echo "Hello-staging"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: docker-build-publish
    if: github.ref == 'refs/heads/prod'
    environment:
      name: "development"
    
    steps:
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: checking deploy
        run: |
          echo "Hello-prod"
